services:
  postgres:
    image: 'postgres:15'
    container_name: nerdy-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - '5432:5432'
    networks:
      - backend
  redis:
    image: 'redis:7.4.2'
    container_name: nerdy-redis
    command: redis-server --save 20 1 --loglevel warning
    ports:
      - '6379:6379'
    volumes:
      - cache:/data
    networks:
      - backend

volumes:
  cache:
    driver: local
networks:
  backend:
    driver: bridge