spring:
  application:
    name: nerdysoft-task
  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    name: ${POSTGRES_DB}
#    url: ${POSTGRES_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  cache:
    type: redis
    cache-names: cache
    redis:
      cache-null-values: false
      time-to-live: 2m
#  data:
#    redis:
#      url: ${REDIS_URL}
springdoc:
  swagger-ui:
    path: /v1/docs